authors = ["William Herrera <wherrera@alahonua.com>"]
name = "SSDPClient"
uuid = "25fcb600-53c2-4b62-becc-06d54d090f43"
version = "0.1.0"

[deps]
Sockets = ""

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"

[targets]
test = ["Pkg", "Test"]
